version: "3"
services:
  db:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    volumes:
      - ./tmp/${COMPOSE_PROJECT_NAME}/fs/mongo:/data/db
    ports:
      - "${MONGO_PORT}:27017"

  cache:
    image: redis:6.2-alpine
    command: redis-server
    ports:
      - "6379:6379"
